# Generated by Django 3.2.3 on 2021-05-28 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0002_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'events'},
        ),
    ]
