# Generated by Django 3.2.3 on 2021-05-28 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0003_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='event_place',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventbookings', to='datarepo.event', verbose_name='event_places'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(choices=[('Karimnagar', 'Karimnagar'), ('Hyderabad', 'Hyderabad'), ('Warangal', 'Warangal')], default=-1.0, max_length=255),
            preserve_default=False,
        ),
    ]
