# Generated by Django 3.2.3 on 2021-05-28 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0004_auto_20210528_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('Karimnagar', 'Karimnagar'), ('Hyderabad', 'Hyderabad'), ('Warangal', 'Warangal')], max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='event_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.eventname'),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='event_place',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.eventplace'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
