# Generated by Django 3.2.3 on 2021-05-28 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0005_auto_20210528_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventname',
            options={'verbose_name_plural': 'event_names'},
        ),
        migrations.AlterModelOptions(
            name='eventplace',
            options={'verbose_name_plural': 'event_places'},
        ),
    ]
